### ISSUE TITLE
Show versions of compilers

### ISSUE THREAD

**Issue by shank03** [ContriHUB/OffCoder#1]
Currently, the drop down shows the hardcoded versions of the compilers.

![Screenshot 2023-10-05 at 8 51 32 AM](https://github.com/ContriHUB/OffCoder/assets/39261691/ecb98e7a-bcda-4ce8-b758-596b0e61db3e)

We need the actual version of compilers.

**Comment by Aqua-16** [comment]
@shank03 Sir could you assign this to me please? I have requested this on ContriHub as well.
