### ISSUE TITLE
Delete from personalized list

### ISSUE THREAD

**Issue by shank03** [ContriHUB/OffCoder#4]
Allow users to delete questions/problems from personalized when they felt cute and might delete later.

**Comment by eleensmathew** [comment]
Hi @shank03 . This is my first time working on a java swing ui tech stack. Do you mind providing some resources so i can understand how to fix this issue better?

**Comment by shank03** [comment]
This isn't swing UI, this is JavaFX, and you can try this maybe 
https://www.codingninjas.com/studio/library/introduction-to-javafx-ui-controls

**Comment by Aqua-16** [comment]
@shank03 Sir I had a quick question. How are you showing that downloaded icon beside the downloaded questions in the list? I couldn't figure that out.

**Comment by shank03** [comment]
@Aqua-16 
https://github.com/ContriHUB/OffCoder/blob/main/src/main/java/com/shank/offcoder/controllers/ProblemCell.java#L80-L82

**Comment by Aqua-16** [comment]
Ah okay sir, got it. Thank you
