### ISSUE TITLE
Delete downloaded questions

### ISSUE THREAD

**Issue by shank03** [ContriHUB/OffCoder#5]
Allow users to delete the downloaded questions (to save some bytes maybe ?).

**Comment by shank03** [comment]
@ELBERLIN You have been assigned to solve this issue

**Comment by Aqua-16** [comment]
@shank03 Sir I would like to work on this. ContriHUB is not currently letting me request this issue eventhough the last date for the previous assignee has passed.

**Comment by shank03** [comment]
@Aqua-16 actually, this issue is already assigned. You'll have wait for a day, or I'll let you know when you can apply.

**Comment by Aqua-16** [comment]
ah alright. Definitely please let me know if the issue becomes availaible again.
