### ISSUE TITLE
Live Submission Status

### ISSUE THREAD

**Issue by shank03** [ContriHUB/OffCoder#6]
Allow users to see status of their submission while they are browsing the problems or viewing the question.
- Submitted
- Waiting
- TestCases passed
- Accepted or which wrong answer

Maybe here ?
![image](https://github.com/ContriHUB/OffCoder/assets/39261691/307e3606-bd5d-442b-aba0-21a7025b46bc)

OR here ?

![image](https://github.com/ContriHUB/OffCoder/assets/39261691/8aa1939b-a43d-4e15-bba2-2be628284681)

**Comment by Aqua-16** [comment]
@shank03 For this problem, are we expected to use the Codeforces API?

**Comment by shank03** [comment]
Maybe ? Maybe not 😎
