### ISSUE TITLE
Move personalized lists panel to right side

### ISSUE THREAD

**Issue by shank03** [ContriHUB/OffCoder#8]
Would make more sense if it were on right side.
![image](https://github.com/ContriHUB/OffCoder/assets/39261691/1d5c3645-40ee-45ac-a60a-24c9e5bc810c)

**Comment by RSGPhoeniX01** [comment]
Hi @shank03 please assign this issue to me.

**Comment by shank03** [comment]
Please request this issue from the website

**Comment by priyanshagra** [comment]
sorry sir , i am not able to solve ,please assign this to someone
